version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
    volumes:
      - ./sql:/docker-entrypoint-initdb.d  # Mount the sql directory into the container

